website/computation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'computation'
urlpatterns = [
        path('', views.index, name = 'index'),
        path('home/', views.home, name = 'home'),
        path('clients/', views.clients, name='clients'),
        path('params/', views.params, name='params'),
        path('queue/', views.queue, name='queue'),
        path('submit/', views.submit, name='submit'),
        path('completed/', views.completed, name='completed'),
        path('details/<str:job>/', views.details, name='details'),
        path('login_user/', views.login_user, name = 'login_user'),
        path('sign_up/', views.sign_up, name = 'sign_up'),
        path('logout_user/', views.logout_user, name = 'logout_user'),
        ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('computation/', include('computation.urls')),
    path('admin/', admin.site.urls),
]

website/computation/models.py
from django.db import models

# Create your models here.

website/computation/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
import socket, select, string, sys, py_compile, os, shelve, sqlite3, time
from django.utils.datastructures import MultiValueDictKeyError
from ftplib import FTP
from subprocess import run

def prompt(request):
    username = request.user.username
    message = "You are connected to the server"
    return render(request, 'computation/home.html', {'username' : username, 'message': message})

def trigger_sock():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    address = ("0.0.0.0",5002)
    ret = sock.connect_ex(address)
    sock.close()
    return ret

def details(request, job):
    submitted = []
    with open(job+"/stderr.txt", "r+") as errfile:
        stderr = errfile.readlines()
    with open(job+"/stdout.txt", "r+") as outfile:
        stdout = outfile.readlines()
    with open(job+"/submit_file.txt", "r+") as subfile:
        lines = subfile.readlines()
    submitted.append(lines[0])
    if lines[1].startswith("data"):
        submitted.append(lines[1])

    for i in range(len(submitted)):
        submitted[i] = submitted[i].split()[2]

    context = {'job_dir': job, 'stderr':stderr, 'stdout':stdout, 'submitted':submitted}
    return render(request, 'computation/details.html', context)

def completed(request):
    all_dirs = os.listdir()
    job_dirs = [x for x in all_dirs if x.startswith("TASK")]
    job_dirs.sort(reverse=True)
    return render(request, 'computation/completed.html', {'jobs':job_dirs})

def submit(request):
    addresses = []
    if request.method == "POST":
        try:
            executable = request.FILES['executable']
        except MultiValueDictKeyError:
            executable = None
        try:
            dataset = request.FILES['dataset']
        except MultiValueDictKeyError:
            dataset = None

        email = request.POST['email']

        selected_client = request.POST['client']

        if executable is not None:
            fs = FileSystemStorage()
            fs.save(executable.name, executable)
        else:
            print("Executable not uploaded")
        if dataset is not None:
            fsd = FileSystemStorage()
            fsd.save(dataset.name, dataset)
        else:
            print("Dataset not uploaded")


        with open("submit_file.txt", "w") as submit_file:
            submit_file.write("executable = "+executable.name+"\n")
            if dataset is not None:
                submit_file.write("data = "+dataset.name+"\n")
            if email is not None:
                submit_file.write("email = "+email+"\n")
            if selected_client != "default":
                submit_file.write("client = "+selected_client[8:])


        with open("fileA.txt", "w") as fileA:
            fileA.write("SUBMIT submit_file.txt")
            fileA.flush()
        is_running = trigger_sock()
    else:
        addresses = ""
        with open("fileA.txt", "w") as fileA:
            fileA.write("a")
        is_running = trigger_sock()
        if is_running == 0:
            while True:
                with open("fileB.txt", "r+") as fileB:
                    if fileB.read(1):
                        fileB.seek(0,0)
                        addresses = fileB.readlines()
                        if len(addresses) > 0 and addresses[0].startswith("addr"):
                            addresses = addresses[1:]
                            if addresses[0].startswith("___"):
                                addresses = []
                            fileB.seek(0,0)
                            fileB.truncate(0)
                            break
                        else:
                            error_message = "Please refresh the page for the information."
                            return render(request, 'computation/clients.html', {'error_message':error_message})
        else:
            return render(request, 'computation/clients.html', {'error_message':"Server is currently closed"})
    active = []
    if len(addresses) != 0:
        for client in addresses:
            if client.startswith("CLIENT"):
                active.append(client)
            if client.startswith("BUSY"):
                break;
    context = {'active':active}
    return render(request, 'computation/submit.html', context)

def queue(request):
    queue_info = ""
    error_message = "Server is currently closed"
    with open("fileA.txt", "w") as fileA:
        fileA.write("JOB-status")
    is_running = trigger_sock()
    if is_running == 0:
        while True:
            with open("fileB.txt", "r+") as fileB:
                if fileB.read(1):
                    fileB.seek(0,0)
                    queue_info = fileB.readlines()
                    if len(queue_info)>0 and queue_info[0].startswith("jobs"):
                        queue_info = queue_info[2:]
                        fileB.seek(0,0)
                        fileB.truncate(0)
                        break
                    else:
                        error_message = "Please refresh the page for the information."
                        return render(request, 'computation/queue.html', {'error_message':error_message})
    else:
        return render(request, 'computation/queue.html', {'error_message':error_message})
    context = {'queue_info':queue_info}
    return render(request, 'computation/queue.html', context)

def params(request):
    statistics = ""
    with open("fileA.txt", "w") as fileA:
        fileA.write("s")
    is_running = trigger_sock()
    if is_running == 0:
        while True:
            with open("fileB.txt", "r+") as fileB:
                if fileB.read(1):
                    fileB.seek(0,0)
                    statistics = fileB.readlines()
                    if len(statistics)>0 and statistics[0].startswith("stats"):
                        statistics = statistics[1:]
                        fileB.seek(0,0)
                        fileB.truncate(0)
                        break
                    else:
                        error_message = "Please refresh the page for the information."
                        return render(request, 'computation/params.html', {'error_message':error_message})
    else:
        return render(request, 'computation/params.html', {'error_message':"Server is currently closed"})
    context = {'statistics':statistics}
    return render(request, 'computation/params.html', context)


def clients(request):
    addresses = ""
    with open("fileA.txt", "w") as fileA:
        fileA.write("a")
    is_running = trigger_sock()
    if is_running == 0:
        while True:
            with open("fileB.txt", "r+") as fileB:
                if fileB.read(1):
                    fileB.seek(0,0)
                    addresses = fileB.readlines()
                    if len(addresses) > 0 and addresses[0].startswith("addr"):
                        addresses = addresses[1:]
                        if addresses[0].startswith("___"):
                            addresses = []
                        fileB.seek(0,0)
                        fileB.truncate(0)
                        break
                    else:
                        error_message = "Please refresh the page for the information."
                        return render(request, 'computation/clients.html', {'error_message':error_message})
    else:
        return render(request, 'computation/clients.html', {'error_message':"Server is currently closed"})
    context = {'addresses':addresses}
    return render(request, 'computation/clients.html', context)

def home(request):
    username = request.user.username
    addresses = ""
    statistics = ""
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    address = ("0.0.0.0",5002)
    is_running = sock.connect_ex(address)
    sock.close()
    if is_running == 0:
        message = "You are connected to the server"
        context = {'username' : username, 'message' : message}
        return render(request, 'computation/home.html', context)
    else:
        print("Server is not running")
        message = "Server is currently closed"
        return render(request, 'computation/home.html', {'username' : username, 'message': message, 'addresses' : addresses, 'statistics' : statistics})
    # print("HOME ENTERED")
    # username = request.user.username
    # addresses = None
    # statistics = None
    # tasks_count = 1
    # client_id = None
    # host = "0.0.0.0"
    # port = 5000
    # s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # s.settimeout(2)
    # # connect to remote host
    # try :
    #     s.connect((host, port))
    # except :
    #     message = "Server is currently closed."
    #     return render(request, 'computation/home.html', {'username' : username, 'message': message})
    #     print('Unable to connect')
    #     sys.exit()
    #
    # conn = sqlite3.connect('db_control.db')
    # cursor = conn.execute("SELECT COUNT(*) FROM UserID")
    # for row in cursor:
    #     if row[0] == 0:
    #         print("NEW USER CONNECTED")
    #         s.send(str.encode("CONTROL"))
    #         break
    #     else:
    #         cursor2 = conn.execute("SELECT Id FROM UserID")
    #         for data in cursor2:
    #             client_id = data[0]
    #             print("\n\n            CONNECTED TO THE SERVER.\n            YOUR ID IS:",str(client_id))
    #             s.send(str.encode("EXISTING_CONTROL"+str(client_id)))
    #             # prompt(request)
    #             break
    #     break
    # conn.close()
    # s.send(str.encode("a"))
    # while 1:

website/computation/templates/computation/base.html
<!doctype html>
{% load static %}
<html lang="en">


  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">

    <link rel="stylesheet" type="text/css" href="{% static 'computation/main.css' %}">

    {% if title %}
      <title>Computation Tool - {{ title }}</title>
    {% else %}
      <title>Computation Tool</title>
    {% endif %}
  </head>
  <body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'computation:home' %}">Computation Tool</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- <a class="nav-item nav-link" href="{% url 'computation:home' %}">Home</a> -->

              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'computation:clients' %}">Active Clients</a>
                <a class="nav-item nav-link" href="{% url 'computation:params' %}">Clients Parameters</a>
                <a class="nav-item nav-link" href="{% url 'computation:queue' %}">Job Queue</a>
                <a class="nav-item nav-link" href="{% url 'computation:submit' %}">Job Submission</a>
                <a class="nav-item nav-link" href="{% url 'computation:completed' %}">Completed Jobs</a>
              {% endif %}

            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'computation:home' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'computation:logout_user' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'computation:login_user' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'computation:sign_up' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %} -->
          {% block content %}{% endblock %}
        </div>

      </div>
    </main>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

website/computation/templates/computation/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="utf-8">

    <link rel="stylesheet" type="text/css" href="{% static 'computation/main.css' %}">

    {% if title %}
      <title>Derivative Trade System - {{ title }}</title>
    {% else %}
      <title>Derivative Trade System</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#">Derivitive Trade System</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'computation:home' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'computation:home' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'computation:home' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'computation:home' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>

      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

website/computation/templates/computation/clients.html
{% extends 'computation/base.html' %}

{% block content %}
{% if error_message %}
<h2>{{error_message}}</h2>
{% else %}
<!-- <h3>Currently active clients:</h3> -->
{% if addresses|length == 0 %}
<table class="content-table">
  <thead>
    <tr>
      <th>NO CLIENTS ARE CURRENTLY CONNECTED</th>
    </tr>
  </thead>
</table>
{% endif %}

<table class="content-table">
  {% for addr in addresses %}
    {% if addr|slice:":4" == 'AVAI' or addr|slice:":4" == 'BUSY' %}

    <thead>
      <tr>
        <th>{{addr}}</th>
      </tr>
    </thead>
    {% else %}
    <tbody>
      <tr>
        <td>{{addr}}</td>
      </tr>
    </tbody>
    {% endif %}
  {% endfor %}

</table>

<!-- {% for addr in addresses %}
{% if addr|slice:":4" == 'AVAI' or addr|slice:":4" == 'BUSY' %}
<br><b>{{ addr }}</b><br>
{%else%}
{{ addr }}<br>
{%endif%}
{% endfor %} -->
{% endif %}
{% endblock %}

website/computation/templates/computation/completed.html
{% extends 'computation/base.html' %}

{% block content %}

<table class="content-table">
  <thead>
    <tr>
      <th>COMPLETED JOBS:</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for j in jobs %}
      <tr>
        <td><a href="{% url 'computation:details' job=j %}">{{ j }}</a></td>
      </tr>
      {% endfor %}
    </tr>
  </tbody>
</table>

<!-- <h1>Completed Jobs:</h1>
{% for j in jobs %}
<li><a href="{% url 'computation:details' job=j %}">{{ j }}</a></li>
{% endfor %} -->
{% endblock %}

website/computation/templates/computation/details.html
{% extends 'computation/base.html' %}

{% block content %}
<h1>Details of completed {{ job_dir }}</h1>

<table class="content-table">
  <thead>
    <tr>
      <th>Submitted files:</th>
    </tr>
  </thead>
  <tbody>
    {% for line in submitted%}
    <tr>
      <td>{{line}}</td>
    </tr>
    {% endfor %}
  </tbody>

  <thead>
    <tr>
      <th>STDERR: <a href="../../{{job_dir}}/stderr.txt" style="text-align:right;float:right;" target="_blank" class="btn btn-info" download>Download</a></th>
    </tr>
  </thead>
  <tbody>
    {% for line in stderr %}
    <tr>
      <td>{{line}}</td>
    </tr>
    {% endfor %}
  </tbody>

  <thead>
    <tr>
      <th>STDOUT: <a href="../../{{job_dir}}/stdout.txt" style="text-align:right;float:right;" target="_blank" class="btn btn-info" download>Download</a></th>
    </tr>
  </thead>
  <tbody>
    {% for line in stdout %}
    <tr>
      <td style="overflow: hidden; width: 280px; text-align: left; valign: top; whitespace: nowrap;">{{line}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!-- <h2>Submitted files:</h2>
{% for line in submitted%}
{{ line }}<br>
{% endfor %}
<br><h2 style="text-align:left;float:left;">STDERR:</h2>
<a href="../../{{job_dir}}/stderr.txt" style="text-align:right;float:right;" target="_blank" class="btn btn-info" download>Download</a><br><br>
{% for line in stderr %}
{{ line }}<br>
{% endfor %}
<br><h2 style="text-align:left;float:left;">STDOUT:</h2>
<a href="../../{{job_dir}}/stdout.txt" style="text-align:right;float:right;" target="_blank" class="btn btn-info" download>Download</a><br><br>
{% for line in stdout %}
{{line}}<br>
{% endfor %} -->

{% endblock %}

website/computation/templates/computation/home.html
{% extends 'computation/base.html' %}


{% block content %}
{% if user.is_authenticated %}
<h1>Hello {{username}}, you are logged in.</h1>
{% else %}
<h1>Hello, please login or register.</h1>
{% endif %}
{% endblock %}

website/computation/templates/computation/index.html
<h1> {{message}} <h1>

<button><a href="{% url 'computation:login_user' %}">Login</a></button>
<button><a href="{% url 'computation:sign_up' %}">Sign up</a></button>

website/computation/templates/computation/login_user.html
{% extends 'computation/base.html' %}

{% block content %}
{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

<h3>Login here:</h3><form method="post" action="{% url 'computation:login_user' %}">
{% csrf_token %}
<label for="username">Username:</label>
<br><input type="text" name="username" placeholder="Username">
<br><br><label for="password">Password:</label>
<br><input type="password" name="password" placeholder="Password">
<br><br><input type="submit" name="" value="Login"></form>

{% endblock %}

website/computation/templates/computation/params.html
{% extends 'computation/base.html' %}
{% load static %}

<!-- <style>
  * {
  font-family: sans-serif; /* Change your font family */
}
</style> -->
<link rel="stylesheet" type="text/css" href="{% static 'computation/main.css' %}">

{% block content %}
{% if error_message %}
<h2>{{error_message}}</h2>
{% else %}
<!-- <h3>Clients' statistics:</h3> -->
{% if statistics|length == 0 %}
<table class="content-table">
  <thead>
    <tr>
      <th>NO CLIENTS ARE CURRENTLY CONNECTED</th>
    </tr>
  </thead>
</table>
{% else %}
<table class="content-table">
  <thead>
    <tr>
      <th>Client</th>
      <th>RAM available</th>
      <th>CPU cores</th>
      <th>Threads</th>
      <th>CUDA compatible GPU</th>
    </tr>
  </thead>
  <tbody>

      {% for line in statistics %}
      {% if line|slice:":6" == 'Client' %}
      <tr>
        <td>{{ line | slice:"7:9" }}</td>
      {% elif line|slice:":3" == 'RAM'%}
        <td>{{ line | slice:"14:"}}</td>
      {% elif line|slice:":3" == 'Num' %}
        <td>{{ line | slice:"20:21"}}</td>
        <td>{{ line | slice:"33:"}}</td>
      {% elif line|slice:":3" == 'CUD' %}
        <td>{{ line | slice:"21:"}}</td>
      </tr>
      {% endif %}
      {% endfor %}

  </tbody>
</table>
{% endif %}

<!-- {% for line in statistics %}
{% if line|slice:":6" == 'Client' %}
<br><b>{{ line }}</b><br>
{% else %}
{{ line }}<br>
{% endif %}
{% endfor %} -->
{% endif %}
{% endblock %}

website/computation/templates/computation/queue.html
{% extends 'computation/base.html' %}

{% block content %}
{% if error_message %}
<h2>{{error_message}}</h2>
{% else %}
<!-- <h3>Queue info:</h3> -->
<table class="content-table">
  {% for line in queue_info %}
  {% if line|slice:":4" == 'ACTI' or line|slice:":4" == 'QUEU'%}
  <thead>
    <tr>
      <th>{{line}}</th>
    </tr>
  </thead>
  {%else%}
  <tbody>
    <tr>
      <td>{{line}}</td>
    </tr>
  </tbody>
  {% endif %}
  {% endfor %}
</table>

<!-- {% for line in queue_info %}
{% if line|slice:":4" == 'ACTI' or line|slice:":4" == 'QUEU'%}
<br><b>{{ line }}</b><br>
{%else%}
{{ line }}<br>
{%endif%}
{% endfor %} -->
{% endif %}
{% endblock %}

website/computation/templates/computation/sign_up.html
{% extends 'computation/base.html' %}

{%block content%}

{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}

<h3>Fill out the form:</h3><form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <label for="email">Email:</label>
  <input type="text" name="email" placeholder="Email">
  <br><input type="submit" name="" value="Register">
</form>

{%endblock%}

website/computation/templates/computation/submit.html
{% extends 'computation/base.html' %}

{% block content %}
<h1>Submit a job:</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label>Executable: </label><br>
  <input type="file" name="executable"><br><br>
  <label>Dataset (optional): </label><br>
  <input type="file" name="dataset"><br><br>
  <label>Enter email to be notified when the job is completed:</label><br>
  <input type="text" name="email"><br><br>
  <label>Select available client (see parameters in Clients Parameters section):</label><br>
  <select name="client">
    <option value="default">default</option>
    {% for client in active %}
    <option value="{{client}}">{{ client }}</option>
    {% endfor %}
  </select><br><br>
  <button type="submit">Start job</button>
</form>
{% endblock %}